//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public string Quote_Type { get; set; }
        public int Quote_ { get; set; }
        public string Contact { get; set; }
        public string Task_Content { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Task_Type { get; set; }
    }
}
